services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - deez-data:/app/data
      - deez-uploads:/app/uploads
    environment:
      - PORT=:3000
      - DATABASE_PATH=/app/data/dz.db
      - MEDIA_STORAGE_PATH=/app/uploads
    restart: unless-stopped

volumes:
  deez-data:
  deez-uploads:
