app = 'deezcore'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[mounts]]
  source = 'deez_data'
  destination = '/app/data'
  initial_size = '1gb'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'

[env]
  PORT = '3000'
  DATABASE_PATH = '/app/data/dz.db'
  MEDIA_STORAGE_PATH = '/app/uploads'